### ISSUE TITLE
Design initial report output

### ISSUE THREAD

**Issue by d33bs** [WayScience/coSMicQC#22]
- Decide on what to include (perhaps as a list of goals for output).
- Sketch what the output should look like.
- Keep PDF pagination in mind (compatibility with PDF and notebook-based output).

Precursor to #2

**Comment by jenna-tomkinson** [comment]
For inspiration: https://github.com/WayScience/Durbin_lab_data/blob/main/2.processing_data/2.single_cell_qc.ipynb

**Comment by d33bs** [comment]
Inspired from Jenna's example, drafted the following (trying to be flexible to one or many features within a threshold set):
<img width="971" alt="image" src="https://github.com/WayScience/coSMicQC/assets/3738008/e3c3992e-3fe6-4eb9-865d-eec43035ba41">

After clicking to "unhighlight" non-outliers, one can see the outliers as patterned traces:
<img width="936" alt="image" src="https://github.com/WayScience/coSMicQC/assets/3738008/597d9cb4-b894-4e41-91c3-a674eda661fe">

I think we'd need one chart per threshold set to make this reproducible, but still thinking through this.

**Comment by d33bs** [comment]
And also, log of the y-axis:
<img width="945" alt="image" src="https://github.com/WayScience/coSMicQC/assets/3738008/20bba696-e548-4cff-8a44-fb4828e2bbb6">
<img width="945" alt="image" src="https://github.com/WayScience/coSMicQC/assets/3738008/052bcfca-338d-4ba7-b6c8-e80e53c3ce2b">
