### ISSUE TITLE
`label_outliers` error

### ISSUE THREAD

**Issue by jenna-tomkinson** [WayScience/coSMicQC#70]
### Is this a duplicate of an existing idea for this project?

- [X] I found no existing [issues](https://github.com/WayScience/coSMicQC/issues) covering this topic.

### What is your idea?

When trying to import `label_outliers` from coSMicQC or just access the function by using `cosmicqc.label_outliers`, I am getting an ImportError and AttributeError.

![image](https://github.com/user-attachments/assets/28ff42a7-e62f-47dc-b461-c568d40d5d0e)

![image](https://github.com/user-attachments/assets/d121920a-dcb0-4cb7-a4aa-5702d36c3354)

From my understanding, this could be due to the `__init__.py` not including the function. Would this be the correct solution?

![image](https://github.com/user-attachments/assets/ce6aad63-b285-4efa-97b8-179cba288d41)

### Would you like to work on a solution for this?

- [X] Yes I am willing to submit a PR for this!

**Comment by d33bs** [comment]
@jenna-tomkinson - double checking, do you think this is able to be closed after the merge of #71? Cheers on the fix!

Aside, if you ever want to close the issue with a PR you can use the special keyword "closes" followed by the numbered reference to close the issue when the PR is merged. [See here for more information](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by jenna-tomkinson** [comment]
Oh my bad! Also that is a super cool thing I didn't know existed haha!

Yes this should be able to be closed, but would we be able to test this in the next release or can we test now?

**Comment by d33bs** [comment]
Closing this as per comments from @jenna-tomkinson (thanks Jenna!). This should be testable and if it's still a problem let's re-raise and address in a new issue.
